### ISSUE TITLE
AutoRCM  + firmlaunch

### ISSUE THREAD

**Issue by Reisyukaku** [nwert/hekate#26]
Seems as though you can't have AutoRCM active while trying to firmlaunch due to the nature of how it does a soft reset. Whoops! 
Not sure how you want to rectify this. Either a message warning the user, or checks i suppose.

**Comment by nwert** [comment]
What exactly is the issue here, the firmware will only soft reset on a panic usually?

**Comment by Reisyukaku** [comment]
Seemed to me that having it on and going to firmlaunch, it'd just go back into rcm.
