### ISSUE TITLE
Switch OS 5.1.0 not supported

### ISSUE THREAD

**Issue by peter17ji** [nwert/hekate#30]
https://gbatemp.net/threads/new-system-update-5-1-0.505827/

**Comment by Jan4V** [comment]
Hekate supports 5.1.0.

**Comment by jerbear64** [comment]
Right, but it can't boot homebrew on 5.1.0.

**Comment by tumGER** [comment]
There is no error with Hekate, the Homebrew Menu is the false of that!

**Comment by jerbear64** [comment]
Homebrew Menu isn't the problem, HBL is.
https://twitter.com/SciresM/status/1002062951434473473

```There're no actual issues with my Loader introduced in 5.1.0 -- seems the issue is in the HBL build people are using (the modified build I usually use works fine, the one being distributed reproduces the hang people have reported).```

**Comment by Jan4V** [comment]
Yeah, and this repo has absolutely nothing to do with HBL.
