### ISSUE TITLE
Sleep mode problem after turning controller off and on - 3.0.0

### ISSUE THREAD

**Issue by BlackThenWhite** [nwert/hekate#36]
There seems to be an issue where, if you remove a controller, turn it off, slide it back into the console then put it into sleep mode, it'll just give a black screen when trying to exit sleep mode. It **_does_** work fine otherwise.

Currently on 3.0.0

**Comment by CTCaer** [comment]
Sleep mode works on your 3.0.0 switch?

**Comment by BlackThenWhite** [comment]
Yeah, sleep mode works perfectly. Besides from when I do the above.

**Comment by BlackThenWhite** [comment]
Just as a reference, here is a video showing sleep mode working.

https://youtu.be/L-P-6Cs9erk

**Comment by CTCaer** [comment]
I had the assumption that sleep mode was completely broken in 3.0.0-3.0.2

Is this behavior reproducible every time?

**Comment by BlackThenWhite** [comment]
I've done testing for about an hour now, it turns out it's not exactly perfect. It's more like it'll work 50/50. It seems random. I had it black screen when I first try to enter sleep mode upon first turning the console on, other times it black screened after the settings and other times after the homebrew launcher closed.

**Comment by DavidBuchanan314** [comment]
Just to add a datapoint, I'm also on 3.0.0 and it doesn't work at all for me. About a second after going into sleep, the backlight turns on (still with a black screen), and the system becomes totally unresponsive.

**Comment by CTCaer** [comment]
@BlackThenWhite 
The PC connection is normal. It disconnects in sleep and after some seconds it connects again and disconnects.
Actually you can see the internal wake up for syncing that way. If sleep mode works.

@DavidBuchanan314 
That is the behavior reported by most users with 3.0.0-3.0.2

@DavidBuchanan314 @BlackThenWhite 
What forks and versions of hekate you both use?

**Comment by DavidBuchanan314** [comment]
I just built from master a couple of days ago, specifically commit `16ac26f583523528f07ec100f65c2933cbe9447f`

**Comment by BlackThenWhite** [comment]
@CTCaer I'm using 2.3 of your compiled version, which was included within this: https://t3chnolog1c.github.io/SwitchGuide/

**Comment by CTCaer** [comment]
So both of you effectively use the same sleep mode config code.

So, you may have different RAM.

I'll make a test payload and see what RAM id you both have.

**Comment by CTCaer** [comment]
I'm back to my build machine.
I could ask you for your fuses, but they contain private info/keys, that's why I wanted a payload.

Please load the following payload:
[iplctc_sdram_id.zip](https://github.com/nwert/hekate/files/2088119/iplctc_sdram_id.zip)

Console Info -> Print fuse info.
Reply back with the two numbers you on top. (Sdram ID: # - #)

**Comment by pulser** [comment]
On another 3.0.2 device with non-functional sleep, the two numbers are shown as `Sdram ID: 0 - 0` (both are zero).

**Comment by CTCaer** [comment]
@pulser 
Yeah, I had another case there with sleep mode partially working. Also with 0 - 0

**Comment by pulser** [comment]
@CTCaer Hmmm interesting - when you say partially, I assume you are meaning it enters sleep, then the screen backlight is enabled? 

The description above sounds like what I see ("About a second after going into sleep, the backlight turns on (still with a black screen), and the system becomes totally unresponsive.")

Let's see if the "working" one has a different RAM ID I suppose

**Comment by CTCaer** [comment]
Nope. This is "not working at all".

I mean cases where user can enter sleep mode, stay there for a couple of minutes and wake the device.
But if they do something else, like here, it breaks.

BTW, @BlackThenWhite 
When sleep mode works, you leave it there and after some time you wake it, correct?

If you press POWER and immediately POWER, that's not sleep mode. It doesn't have the chance to enter it. It just turns off the screen and re-enables it.

**Comment by pulser** [comment]
OK I see what you mean @CTCaer - so it sounds like the RAM ID is not the defining factor (at least not from a couple of data points), if you have had a device with working-ish sleep on 0-0.

**Comment by pulser** [comment]
I guess good news in that we're not facing a strange "rare" hardware config to support/think about forever more. But quite intriguing there's no obvious reason for one device to work and another not to.

**Comment by CTCaer** [comment]
I'm waiting for @BlackThenWhite and we'll find out why.

I think it's a misundestanding:

> If you press POWER and immediately POWER, that's not sleep mode. It doesn't have the chance to enter it. It just turns off the screen and re-enables it.

I run into it, some times before, when I fixed the lp0 config's order of variables.
But I quickly understood and became disappointed that this instant sleep/wake up, was only the sceen turning off/on and no sleep.

**Comment by CTCaer** [comment]
@pulser 
The 3.0.2 case with a partial working sleep mode, was not a sleep mode.
It was what I said. Screen turning off/on and no time for sleep mode state entering.

**Comment by pulser** [comment]
Alrighty! So hopefully we have something simpler to blame - warmboot config or LP0 setup?

**Comment by BlackThenWhite** [comment]
Mine was also `0-0`.

I think the longest I left it was about 30 seconds, I'll leave it for a while a few times and see if there's any difference.

**Comment by BlackThenWhite** [comment]
Alright, from the looks of it it may not have entered sleep mode. I figured that holding down the power button and putting it into sleep mode would put it into a sleep state right away, seems I was wrong.

**Comment by CTCaer** [comment]
So if you press POWER once, or the sleep icon in horizon OS, the device cannot sleep, correct?

**Comment by BlackThenWhite** [comment]
That is correct. I thought it entered the sleep state right away, I didn't know that it took a bit.

**Comment by thanausator** [comment]
Just tested the latest commit (https://github.com/nwert/hekate/commit/486a121cbf56b720a239d12424ee7f7c6ced4b6e) on a 3.0.2 switch.
When you press the POWER button, the screen turns off as expected.
Then after a short timeout (just a few seconds) the backlight turns on, with the screen remaining black.

**Comment by CTCaer** [comment]
Thanks for testing the latest commit.

I'll close this as duplicate
